name: Node.js CI/CD

on:
  push:
    branches:
      - main  # Change this to your main branch if different

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'  # Specify your Node.js version

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Deploy to server
        env:
          PORT: ${{ secrets.PORT }}
          DB_URL: ${{ secrets.DB_URL }}
          STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}
          CLIENT_URL: ${{ secrets.CLIENT_URL }}
        uses: appleboy/scp-action@master
        with:
          port: 22
          source: "."
          target: "./"